src/content/clients/content-client.js
src/content/fetch-content.js
tests/spec/content/clients/content-client.js

Improvements to ContentClient

---

bower.json
package.json
src/content/state-to-content.js
src/content/types/livefyre-youtube-content.js
tests/spec/content/state-to-content.js

https://livefyre.atlassian.net/browse/LF-19973

LF-19973: Use url content view if youtube

---

bower.json

https://livefyre.atlassian.net/browse/LF-20178

LF-20178: Bumping share version

---

src/content/views/gallery-attachment-list-view.js

https://livefyre.atlassian.net/browse/LF-20349

LF-20349 setting iframe video height and width

---

src/content/types/livefyre-url-content.js
tests/fixtures/url-type-content.json
tests/spec/content/types/livefyre-url-content.js

https://livefyre.atlassian.net/browse/LF-21161

LF-21161: Link titles for url content

---

bower.json
package.json

https://livefyre.atlassian.net/browse/LF-21183

LF-21183: Bumping share version

---

bower.json
package.json
src/content/views/content-view.js
src/content/views/livefyre-content-view.js
src/content/views/twitter-content-view.js

https://livefyre.atlassian.net/browse/LF-20668

LF-20668: Fixing missing twitter controls in IE11

---

bower.json
package.json
src/content/types/livefyre-content.js
src/content/util.js
tests/spec/content/types/livefyre-content.js
tests/spec/content/util.js
tests/spec/content/views/content-list-view.js

https://livefyre.atlassian.net/browse/LF-21199

LF-21199: Linkifying content bodies

---

src/content/css/mixins/content-structure.less
src/content/templates/oembed-link.mustache
src/css/style.less

https://livefyre.atlassian.net/browse/LF-19426
Modified mustache file for better look of media wall if no thumbnail.

LF-19426 : Content with link attachments but no thumbnail look ugly in Media Wall

---

bower.json
package.json
requirejs.conf.js
src/impressionUtil.js

(issue when loaded into designer)

need to inject twitter script after all

---

bower.json
package.json
src/content/state-to-content.js
src/content/types/livefyre-content.js

https://livefyre.atlassian.net/browse/LF-19379

LF-19379 adding support for youtube to sdk apps

---

.travis.yml
Makefile
package.json

add make lessc target and add travis ci check that lessc wass run

LF-21484: add make lessc target and add travis ci check for lessc

---

src/collection/clients/bootstrap-client.js
tests/spec/collection/clients/bootstrap-client.js

this depends on an HAProxy config change which will be merged to production on Thursday 3/17

Bootstrap init => Fastly / data.livefyre.com [DNM until after 3/17]

---

bower.json
package.json
requirejs.conf.js
src/collection/clients/translation-client.js
src/collection/main.js
src/content/views/mixins/livefyre-content-view-mixin.js
src/i18n.js
src/views/show-more-button.js
tests/spec/collection/clients/translation-client.js
tests/spec/content/views/content-list-view.js
tests/spec/i18n.js

https://livefyre.atlassian.net/browse/LF-22010

LF-22010: Adding i18n module

---

bower.json
package.json
src/content/templates/content-body.mustache
src/content/views/content-body-view.js

https://livefyre.atlassian.net/browse/LF-22790

LF-22790: Adding translations for featured content

---

bower.json
package.json
src/util.js

https://livefyre.atlassian.net/browse/LF-23206

LF-23206: Adding binarySearch function to SDK

---

bower.json
package.json
src/content/views/gallery-attachment-list-view.js
src/modal/views/attachment-gallery-modal.js
tests/spec/modal/views/attachment-gallery-modal.js

https://livefyre.atlassian.net/browse/LF-22035

LF-22035: Fixing more attachment resize issues

---

src/collection/clients/http-client.js
tests/spec/collection/clients/bootstrap-client.js
tests/spec/collection/clients/create-client.js
tests/spec/collection/clients/stream-client.js
tests/spec/collection/clients/translation-client.js
tests/spec/collection/clients/write-client.js
tests/spec/content/clients/content-client.js

https://livefyre.atlassian.net/browse/LF-23479

LF-23479 switching api calls to always be https, updating tests

---

bower.json
package.json
src/content/views/gallery-attachment-list-view.js
src/modal/views/attachment-gallery-modal.js
tests/spec/content/views/gallery-attachment-list-view.js
tests/spec/modal/views/attachment-gallery-modal.js

https://livefyre.atlassian.net/browse/LF-23333
https://livefyre.atlassian.net/browse/LF-23500

Fixing attachment click and resize bugs

---

src/collection/clients/http-client.js

https://livefyre.atlassian.net/browse/LF-23479

LF-23479 fixing an error tests in the apps uncovered

---

src/modal/views/attachment-gallery-modal.js
tests/spec/modal/views/attachment-gallery-modal.js

https://livefyre.atlassian.net/browse/LF-23333

LF-23333: Improve landscape support for attachment modal

---

bower.json
package.json
src/content/views/gallery-attachment-list-view.js
tests/spec/content/views/gallery-attachment-list-view.js

https://livefyre.atlassian.net/browse/LF-23333

LF-23333: Video post

---

bower.json
package.json

https://livefyre.atlassian.net/browse/LF-23439

LF-23439 ui version for button key event

---

bower.json
package.json
src/ui/hub-like-button.js
src/ui/hub-toggle-button.js

https://livefyre.atlassian.net/browse/LF-23439

LF-23439 fixing key events on buttons

---

bower.json
package.json
src/content/content-header-view-factory.js
tests/spec/content/content-header-view-factory.js

Support the case where there is no display name

---

bower.json
examples/contentview/index.html
package.json
src/content/views/content-body-view.js
tests/spec-list.js
tests/spec/content/views/content-body-view.js

https://jira.corp.adobe.com/browse/FYR-651

FYR-651: Do not display title of content if oembed link already has title

---

bower.json
package.json
src/content/views/content-header-view.js
src/util.js

This avoids blocking .height calls for a faster render.

Use request animation frame for header image calculation

---

bower.json
package.json
src/content/views/single-attachment-view.js

https://jira.corp.adobe.com/browse/FYR-1159

required jquery missing

---

bower.json
package.json
src/collection/main.js
src/collection/sorted.js
src/content/css/modal-content-card.less
src/content/templates/carousel-content-view.mustache
src/content/views/carousel-content-view.js
src/content/views/mixins/attachment-modal-mixin.js
src/modal/css/modal.less
src/util.js
tests/spec/collection/fake.js
tests/spec/content/views/carousel-content-view.js
tests/spec/content/views/mixins/attachment-modal-mixin.js

https://jira.corp.adobe.com/browse/FYR-1875

FYR-1875: Carousel modal view

---

bower.json
package.json
src/content/views/content-view.js
src/content/views/modal-content-card-view.js

https://jira.corp.adobe.com/browse/FYR-1342

FYR-1342: Show text-only content views

---

bower.json
package.json
src/content/views/product-content-view.js

https://jira.corp.adobe.com/browse/FYR-3134

FYR-3134: Fixing product carousel positioning issue

---

bower.json
package.json
src/content/views/content-view.js
src/content/views/modal-content-card-view.js

1. Toggle treats undefined as true
2. Content with link attachments looks weird in modal

Fixing issues

---

bower.json
package.json
src/content/templates/product-block.mustache
src/content/views/product-block-view.js
tests/spec/content/views/modal-content-card-view.js
tests/spec/content/views/product-block-view.js

https://jira.corp.adobe.com/browse/FYR-3772
Adding product images separately so that they can be verified before being added to the DOM in case they are broken or don’t exist.

FYR-3772: Adding product images separately

---

bower.json
package.json
src/collection/sorted.js
src/content/templates/spectrum/content-header.mustache
src/content/views/attachment-carousel-view.js
src/content/views/mixins/media-mask-mixin.js

https://jira.corp.adobe.com/browse/FYR-5822

FYR-5822: Fixing tab indexing

---

bower.json
package.json
src/content/templates/content-body.mustache
src/content/templates/product-carousel.mustache
src/content/templates/spectrum/content-header.mustache
src/content/util/main.js
src/content/views/attachment-carousel-view.js
src/content/views/carousel-content-view.js
src/content/views/content-body-view.js
src/content/views/mixins/attachment-modal-mixin.js
src/content/views/oembed-view.js
src/content/views/product-carousel-view.js
src/content/views/spectrum/content-header-view.js
src/content/views/tiled-attachment-list-view.js
src/util/date.js

1. Image aria-label should be different in modal than on cards
2. Product carousel navigation arrows should be usable via keyboard
3. Text content of cards should be usable via keyboard / screen readers
4. Relative created timestamps should be understandable

Accessibility updates

---

bower.json
package.json
src/content/views/media-mask.js

https://jira.corp.adobe.com/browse/FYR-8028

FYR-8028: Adding support for permalink

---

bower.json
package.json
src/content/views/content-list-view.js

https://jira.corp.adobe.com/browse/FYR-7910

FYR-7910: Don’t shift content if there is no animation

---

bower.json
package.json
src/content/content-header-view-factory.js

https://jira.corp.adobe.com/browse/FYR-5822

FYR-5822: Removing unnecessary twitter author url endpoint

---

bower.json
package.json
src/content/views/carousel-content-view.js

https://jira.corp.adobe.com/browse/FYR-11465

FYR-11465: Fix modal orientation

---

bower.json
package.json
src/collection/streams/archive-query.js

share sortOrder
https://jira.corp.adobe.com/browse/FYR-11820

FYR-11820: Update archive-query.js

---

bower.json
package.json
src/content/types/livefyre-instagram-content.js

https://jira.corp.adobe.com/browse/FYR-12040

FYR-12040: Fix unsupported function

---

bower.json
package.json
src/auth/clients/livefyre-auth-client.js

https://jira.corp.adobe.com/browse/FYR-11776

FYR-11776: Fix HTTPS for auth client
